name: flutter_app_name
description: A package that makes it easy to set your flutter app launcher name. 
version: 0.1.1+packagename
maintainer: Frankie Primerano (@f-prime) 
homepage: https://github.com/f-prime/flutter_app_name

dependencies:
  yaml: ^3.1.0
  xml: ^6.0.1
  rename: ^3.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.16.6

flutter_app_name:
  name: "Flutter App Name"
